CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50)
);

CREATE TABLE quizzes(
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);